<<<<<<< HEAD
# Generated by Django 5.2.8 on 2025-11-18 12:08

import django.db.models.deletion
from django.db import migrations, models
=======
# Generated by Django 4.2.7 on 2023-12-08 19:15

from django.db import migrations, models
import django.db.models.deletion
>>>>>>> 2ba51bd7aedb01a9c2cd58ad71fcf614016630fc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=10, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
=======
>>>>>>> 2ba51bd7aedb01a9c2cd58ad71fcf614016630fc
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50, null=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=10)),
                ('address', models.TextField(null=True)),
                ('prn', models.CharField(max_length=20, null=True)),
<<<<<<< HEAD
                ('image', models.ImageField(null=True, upload_to='stud_app/images')),
=======
>>>>>>> 2ba51bd7aedb01a9c2cd58ad71fcf614016630fc
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.department')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stud_app.year')),
            ],
        ),
    ]
