# Generated by Django 4.2.7 on 2023-12-12 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stud_app', '0002_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='image',
            field=models.ImageField(null=True, upload_to='student/images/%Y-%m-%d/'),
        ),
    ]
